/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATM03;

import ATM03.CajeroAutomatico.model.ATM;
import ATM03.CuentasManager.models.CuentasManager;
import ATM03.entities.Cuenta;
import ATM03.repositories.HashMapBinFileCuentasRepository;
import ATM03.repositories.interfaces.ICuentasRepository;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    ATM elATM = new ATM();
    elATM.run();
// 
//     String filePath = "archivo.bin";
//     ICuentasRepository repo = HashMapBinFileCuentasRepository.obtenerInstancia(filePath);
//     CuentasManager manager = new CuentasManager(repo);
// 
//     Cuenta c1 = new Cuenta(777, 123, 70000, 70000);
//     Cuenta c2 = new Cuenta(12345, 54321, 700, 700);
//     Cuenta c3 = new Cuenta(1111, 1111, 300, 300);
// 
// 
//     manager.crearCuenta(c1);
//     manager.crearCuenta(c2);
//     manager.crearCuenta(c3);

  }
}
